"""initial

Revision ID: 1ea5e20545a6
Revises: 
Create Date: 2026-10-05 20:47:35.754224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ea5e20545a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_link_types')),
    sa.UniqueConstraint('name', name=op.f('uq_link_types_name'))
    )
    op.create_table('note_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note_types')),
    sa.UniqueConstraint('name', name=op.f('uq_note_types_name'))
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('note_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_type_id'], ['note_types.id'], name=op.f('fk_notes_note_type_id_note_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('link_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['link_type_id'], ['link_types.id'], name=op.f('fk_links_link_type_id_link_types')),
    sa.ForeignKeyConstraint(['source_id'], ['notes.id'], name=op.f('fk_links_source_id_notes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['notes.id'], name=op.f('fk_links_target_id_notes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_links')),
    sa.UniqueConstraint('source_id', 'target_id', 'origin', 'link_type_id', name='uq_note_link')
    )
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_links_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_links_target_id'), ['target_id'], unique=False)

    op.create_table('note_has_tags',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_note_has_tags_note_id_notes')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_note_has_tags_tag_id_tags')),
    sa.PrimaryKeyConstraint('note_id', 'tag_id', name=op.f('pk_note_has_tags'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_has_tags')
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_links_target_id'))
        batch_op.drop_index(batch_op.f('ix_links_source_id'))

    op.drop_table('links')
    op.drop_table('notes')
    op.drop_table('tags')
    op.drop_table('note_types')
    op.drop_table('link_types')
    # ### end Alembic commands ###
